classDiagram
    class adminDTO {
        +email : string
        +id : string
        +role : bool
    }

    class VerifyAdmin {
        +isConnected(adminDTO)
        +isAdmin(adminDTO)
    }

    class AdminRepository {
        +getMessages()
        +getUsers()
    }

    %% Relations
    VerifyAdmin --> adminDTO : utilise
    VerifyAdmin --> AdminRepository : accède 
